#!/bin/bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: GPL-2.0

# Cleanup all the files generated by the different metric collectors.
# Call the respective collector specific cleanup code one by one
sudo DAMOOS="$DAMOOS" bash "$DAMOOS"/metrics_collector/collectors/rss/rss_cleanup.sh
sudo DAMOOS="$DAMOOS" bash "$DAMOOS"/metrics_collector/collectors/swapout/swapout_cleanup.sh
sudo DAMOOS="$DAMOOS" bash "$DAMOOS"/metrics_collector/collectors/swapin/swapin_cleanup.sh
sudo DAMOOS="$DAMOOS" bash "$DAMOOS"/metrics_collector/collectors/runtime/runtime_cleanup.sh
